Fix UI of dialog boxes
versus-project/versus-app pull request #305
Opened 2023-05-20 13:56 UTC by Adam-GitHub0

2023-05-22 18:17 UTC, hamzaremmal requested changes
Can you make the background of the text invisible, so we can only have white text over blue background instead of the grey or white one.

![adam](https://github.com/cs306-versus/versus-app/assets/56235032/952594ba-46a6-4ef7-81fe-90c5308d1841)

2023-05-22 18:35 UTC, Adam-GitHub0 commented
> Can you make the background of the text invisible, so we can only have white text over blue background instead of the grey or white one.
> 
> ![adam](https://user-images.githubusercontent.com/56235032/239997286-952594ba-46a6-4ef7-81fe-90c5308d1841.png)

Okay , I changed it in the last commit !

2023-05-22 20:30 UTC, hamzaremmal approved these changes

2023-05-22 20:30 UTC, merged

2023-05-24 11:46 UTC, Adam-GitHub0 commented on app/src/main/java/com/github/versus/announcements/ChoosePostSportDialogFragment.java
> +    @Override
This code is refactored in the next pull request .

2023-05-24 11:48 UTC, Adam-GitHub0 commented on app/src/main/java/com/github/versus/announcements/ChoosePostSportDialogFragment.java
> +    public void onStart() {
This method and the one above is refactored in the next P.R