Added layout and day buttons for schedule
versus-project/versus-app pull request #36
Opened 2023-03-12 11:41 UTC by aymanelamyaghri

2023-03-15 18:03 UTC, hamzaremmal requested changes
Tests  are missing, lets work on that so we can get this PR merged :-)

2023-03-16 08:36 UTC, ktotam1 commented on app/src/main/java/com/github/versus/MyAdapter.java
what does MyAdapter do? not clear from class name

2023-03-16 19:18 UTC, aymanelamyaghri commented on app/src/main/java/com/github/versus/MyAdapter.java
Fixed this issue !

2023-03-16 19:38 UTC, hamzaremmal approved these changes
let's get this merge :-)

2023-03-16 19:39 UTC, merged